# HTML
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(cae0c97a-074f-470f-921a-e09250a693a5)'
    appType: 'webAppLinux'
    WebAppName: 'demohtml'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PHP:8.2'
    DeploymentTypeLinux: 'oneDeploy'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(cae0c97a-074f-470f-921a-e09250a693a5)'
    appType: 'webAppLinux'
    appName: 'demohtml'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PHP:8.1'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(cae0c97a-074f-470f-921a-e09250a693a5)'
    appType: 'webAppLinux'
    WebAppName: 'demohtml'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PHP:8.2'
    DeploymentTypeLinux: 'oneDeploy'
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
